/* Criando o Banco de Dados Livraria */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

/* Criando a tabela Livros */

CREATE TABLE LIVROS(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PÁGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2), 
	ANO INT(4)
);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('CAVALEIRO REAL','ANA CLÁUDIA','F',465,'ATLAS',49.9,'RJ',2009); 
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('SQL PARA LEIGOS','JOÃO NUNES','M',450,'ADDISON',98,'SP',2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('RECEITAS CASEIRAS','CÉLIA TAVAREZ','F',210,'ATLAS',45,'RJ',2008);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('PASSOAS EFETIVAS','EDUARDO SANTOS','M',390,'BETA',78.99,'RJ',2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('HABITOS SAUDÁVEIS','EDUARDO SANTOS','M',630,'BETA',150.98,'RJ',2019);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('A CASA MARROM','HERMES MACEDO','M',250,'BUBBA',60,'MG',2016);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('ESTÁCIO QUERIDO','GERALDO FRANCISCO','M',310,'INSIGNIA',100,'ES',2015);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('PRA SEMPRE AMIGAS','LEDA SILVA','F',510,'INSIGNIA',78.98,'ES',2011);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('COPAS INESQUECÍVEIS','MARCO ALCÂNTARA','M',200,'LARSON',130.98,'RS',2018);
INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PÁGINAS, EDITORA, VALOR, UF, ANO) VALUES('O PODER DA MENTE','CLARA MAFRA','F',120,'CONTINENTAL',56.58,'RS',2017);

/* TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E O NOME DA EDITORA */
SELECT LIVRO, EDITORA FROM LIVROS;

/* TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO */
SELECT LIVRO, UF FROM LIVROS
WHERE SEXO = 'M';

/* TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINA DOS LIVROS PUBLICADOS  POR AUTORES DO SEXO FEMININO */
SELECT LIVRO, PÁGINAS FROM LIVROS
WHERE SEXO ='F';

/* TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO */
SELECT LIVRO, VALOR FROM LIVROS
WHERE UF = 'RS';
SELECT LIVRO, UF, VALOR FROM LIVROS /* CONFERINDO INSERINDO O UF */
WHERE UF = 'RS';

/* TRAZER OS VALORES DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO */
SELECT AUTOR, SEXO, UF 
FROM LIVROS
WHERE 
SEXO = 'M' AND (UF = 'RS' OR UF = 'RJ');






  
 
 
 

 


 
 
